version: "3"
services:
  wordpress:
    build: requirements/wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: ssadiki
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - wordpress:/wordpress
    networks:
      - inception
      - backend
    restart: always
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    ressources:
      requests:
        memory: "256Mi"
      limits:
        memory: "900Mi"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ssadiki
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend
    restart: always
  nginx:
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/wordpress
    networks:
      - inception
      - backend
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
    driver: bridge
  backend:
volumes:
  wordpress:
  mysql:
