version: "3"
services:
  wordpress:
    build: requirements/wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/wordpress
    networks:
      - inception
    restart: always
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - inception
    restart: always
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
    driver: bridge
volumes:
  wordpress:
  mysql:
